version: '3'
services:
  kwok-cluster:
    image: registry.k8s.io/kwok/cluster:v0.4.0-k8s.v1.28.0
    ports:
      - "8080:8080"
    networks:
      - my-network

  pytorch-container:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: aaml_kwok:latest
    user: appuser
    ports:
      - "8888:8888"
      - "6006:6006"
    networks:
      - my-network
    depends_on:
      - kwok-cluster
    volumes:
    - ./logs:/home/appuser/logs
    - ./tlogs:/home/appuser/tlogs
    - ./models:/home/appuser/models
    - ./deployment_data:/home/appuser/deployment_data
    - ./scripts:/home/appuser/scripts
    - ./data:/home/appuser/data
    - ./notebooks:/home/appuser/notebooks

networks:
  my-network:
