version: '3'
services:
  kwok-cluster:
    image: registry.k8s.io/kwok/cluster:v0.4.0-k8s.v1.28.0
    ports:
      - "8080:8080"
    networks:
      - my-network

  pytorch-container:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: aaml_kwok:latest
    user: appuser
    ports:
      - "8888:8888"
      - "6006:6006"
    networks:
      - my-network
    depends_on:
      - kwok-cluster


networks:
  my-network:
