apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    kwok.x-k8s.io/node: fake
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: kwok-gpu-node
    kubernetes.io/os: linux
    kubernetes.io/role: gpu-agent
    node-role.kubernetes.io/gpu-agent: ""
    type: kwok
  name: kwok-gpu-node
spec:
  taints:
  - effect: NoSchedule
    key: kwok.x-k8s.io/node
    value: fake
status:
  allocatable:
    cpu: "4"
    memory: "16Gi"
    pods: "110"
    nvidia.com/gpu: "2"
  capacity:
    cpu: "4"
    memory: "16Gi"
    pods: "110"
    nvidia.com/gpu: "2"
  nodeInfo:
    architecture: amd64
    bootID: ""
    containerRuntimeVersion: ""
    kernelVersion: ""
    kubeProxyVersion: fake
    kubeletVersion: fake
    machineID: ""
    operatingSystem: linux
    osImage: ""
    systemUUID: ""
  phase: Running
